localizer:
  enabled: true
  subscribe_endpoint: "tcp://127.0.0.1:5560"
  subscribe_topic: "meas"
  rcvhwm: 128
  linger_ms: 0
  batch_timeout_s: 0.25
  max_round_age_s: 1.0
  min_anchors: 4
  total_anchors: 4
  console: true
  pose_zmq:
    enabled: true
    endpoint: "tcp://0.0.0.0:5561"
    bind: true
    topic: "pose"
    sndhwm: 32
    linger_ms: 0
  filter_window: 5

layout:
  anchors:
    ANCHOR:A: [0.0, 0.0]
    ANCHOR:B: [0.0, 3.0]
    ANCHOR:C: [4.0, 3.0]
    ANCHOR:D: [4.0, 0.0]

# if 3d localisation working
# layout:
#   anchors:
#     ANCHOR:A: [0.0, 0.0, 0.0]
#     ANCHOR:B: [0.0, 3.0, 2.0]
#     ANCHOR:C: [4.0, 3.0, 0.0]
#     ANCHOR:D: [4.0, 0.0, 0.0]
